mgirlich/tibblify

src/Path.h
src/collector-method.cpp

Pass SEXP instead of pointer to SEXP

---

R/utils.R
src/collector-method.cpp
tests/testthat/_snaps/tibblify.md
tests/testthat/test-tibblify.R

All error messages show path

---

R/shape_utils.R
tests/testthat/test-guess_spec.R
tests/testthat/test-shape_utils.R

if all other conditions apply.

Detect lists of length one as object lists

---

src/Path.h
src/collector-method.cpp

Fix protection errors

---

src/collector-method.cpp

as the former are undefined across function boundaries.
This is the largest and messiest PR from #51 (but also difficult to disentangle), I'll double-check if it's necessary to weed out the protection errors.

Replace PROTECT() and UNPROTECT() with cpp11 protection

---

R/shape_utils.R

Prefer detect_index() over any(map())

---

DESCRIPTION
R/format.R

Replace crayon by cli

---

R/spec_guess.R
R/spec_guess_df.R
R/spec_guess_list.R
R/spec_guess_object.R
R/spec_guess_object_list.R
man/spec_guess.Rd
tests/testthat/test-spec_guess_df.R
tests/testthat/test-spec_guess_object.R
tests/testthat/test-spec_guess_object_list.R

Test empty lists

---

DESCRIPTION
R/tibblify.R
tests/testthat/test-tibblify.R

Order field names in C locale

---

R/spec_guess_object.R
R/spec_guess_object_list.R
man/spec_guess.Rd
tests/testthat/test-spec_guess_object.R
tests/testthat/test-spec_guess_object_list.R

`spec_guess()` can guess vector `input_form`

---

R/spec_guess_df.R
tests/testthat/test-spec_guess_df.R

Add fast path to `spec_guess_df()`

---

src/collector-method.cpp
src/utils.h

Add missing `PROTECT()` around `R_tryEval()`

---

R/format.R
R/spec_guess.R
R/tibblify.R
man/formatting.Rd
man/tibblify.Rd
tests/testthat/_snaps/spec_guess.md
tests/testthat/test-tibblify.R

Add `unspecified` argument to `tibblify()`

---

R/utils.R
src/collector-method.cpp
tests/testthat/_snaps/tibblify.md
tests/testthat/test-tibblify.R

Check that names are not `NULL` for `input_form = "object"`

---

R/tib_spec.R
man/tib_scalar.Rd
tests/testthat/_snaps/tib_spec.md
tests/testthat/test-tib_spec.R
tests/testthat/test-tibblify.R

Allow `names_to` for input form vector

---

DESCRIPTION

Add myself as contributor

---

src/collector-method.cpp
tests/testthat/test-tibblify.R

Keep protecting value

---

DESCRIPTION
R/spec_guess_object_list.R
R/tib_spec.R
R/utils.R
man/spec_df.Rd
src/collector-method.cpp
src/conditions.h
src/shared-objects.c
src/tibblify.h
src/utils.h
tests/testthat/_snaps/tib_spec.md
tests/testthat/_snaps/tibblify.md
tests/testthat/helper-functions.R
tests/testthat/test-tib_spec.R
tests/testthat/test-tibblify.R

Support column major form

---

src/collector-method.cpp
tests/testthat/test-tibblify.R

Elements with `NULL` triggered an incorrect required error

Handle NULL in Multi Collector

---

R/zzz.R
src/tibblify.h

Remove slider references

---

NEWS.md
R/format.R
R/tib_spec.R
man/tib_scalar.Rd
src/collector-method.cpp
src/utils.h
tests/testthat/_snaps/format.md
tests/testthat/test-format.R
tests/testthat/test-tibblify.R

Add `elt_transform`
